<a href="https://colab.research.google.com/github/Aaksha-sharma/Linear-Regression-multivariate/blob/main/Linear_regression_Multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [21]:
dt=pd.read_csv('/content/homeprices.csv')
dt

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
#handling null value
import math
dt.bedrooms.median()

4.0

In [9]:
dt.bedrooms=dt.bedrooms.fillna(dt.bedrooms.median())
dt

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
model=linear_model.LinearRegression()
new_dt = dt.drop('price',axis='columns')
model.fit(new_dt,dt.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
model.predict([[3000,3,40]])

array([498408.25158031])

In [17]:
m=model.coef_
print(m)

[  112.06244194 23388.88007794 -3231.71790863]


In [15]:
model.intercept_

221323.00186540396

In [19]:
price= 3000 * m[0]+3 * m[1]+40 *m[2] + model.intercept_
print(price)

498408.2515803067


In [20]:
model.predict([[2500,4,5]])

array([578876.03748933])